
one-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one1.out -p one1.top -c one1.crd

two-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one2.out -p two1.top -c two1.crd

three-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one3.out -p three1.top -c three1.crd

four-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one4.out -p four1.top -c four1.crd

four2-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one4-2.out -p four2.top -c four2.crd

five-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one5.out -p five1.top -c five1.crd

six-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one6.out -p six1.top -c six1.crd

seven-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one7.out -p seven1.top -c seven1.crd

eight-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one8.out -p eight1.top -c eight1.crd

nine-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one9.out -p nine1.top -c nine1.crd

ten-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one10.out -p ten1.top -c ten1.crd

eleven-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one11.out -p eleven1.top -c eleven1.crd

twelve-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one12.out -p twelve1.top -c twelve1.crd

thirteen-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one13.out -p thirteen1.top -c thirteen1.crd

fourteen-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one14.out -p fourteen1.top -c fourteen1.crd

fifteen-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-one15.out -p fifteen1.top -c fifteen1.crd

four1-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-four1.out -p four-leap1.top -c four-leap1.crd

four1-amber-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-four1-leap.out -p prmtop -c inpcrd

four-water-cando-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-four-cando.out -p solvated_four.top -c solvated_four.crd

four-water-leap-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-four-leap.out -p solvated_four_leap.top -c solvated_four_leap.crd

