
cando-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-cando.out -p lyz-cando.parm7 -c lyz-cando.rst7

leap-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-leap.out -p lyz-leap.top -c lyz-leap.crd

cando-water-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-cando-water.out -p solvated_lyz-cando.parm7 -c solvated_lyz-cando.rst7

leap-water-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-leap-water.out -p solvated-lyz-leap.top -c solvated-lyz-leap.crd
