
cando-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-cando.out -p lyz-cando.parm7 -c lyz-cando.rst7

leap-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-leap.out -p lyz-leap.top -c lyz-leap.crd

cando-water-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-cando-water.out -p solvated_lyz-cando.parm7 -c solvated_lyz-cando.rst7

leap-water-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-leap-water.out -p solvated-lyz-leap.top -c solvated-lyz-leap.crd

cando-4hb1-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-4hb1-cando.out -p solvated-4hb1.top -c solvated-4hb1.crd

leap-4hb1-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-4hb1-leap.out -p solvated-4hb1-leap.top -c solvated-4hb1-leap.crd

cando-2rjv-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-2rjv-cando.out -p solvated-2rjv-cando.top -c solvated-2rjv-cando.crd

leap-2rjv-run:
	$(HOME)/Development/amber18/bin/sander -O -i md.in -o md-2rjv-leap.out -p solvated-2rjv-leap.top -c solvated-2rjv-leap.crd
