(COMMON-LISP:LOAD "source-dir:extensions;cando;src;lisp;start-cando.lisp")
(QUICKLISP-CLIENT:QUICKLOAD :FEP)
(LEAP:SETUP-AMBER-PATHS)
(LEAP:SOURCE "leaprc.ff14SB.redq")
(LEAP:SOURCE "leaprc.gaff")
(LEAP:LOAD-AMBER-PARAMS "frcmod.ionsjc_tip3p")
(QUICKLISP-CLIENT:QUICKLOAD :FEP)
(FEP:LOAD-FEPS "postcharge/feps.cando")
(COMMON-LISP:DEFPARAMETER FEP::LSOLV (CANDO:LOAD-MOL2 "AA-AB/ligand/solvated.mol2"))
(COMMON-LISP:DEFPARAMETER FEP::LSOURCE (CANDO:LOAD-MOL2 "AA-AB/ligand/source.mol2"))
(COMMON-LISP:DEFPARAMETER FEP::DECHARGE
  (CANDO:COMBINE (CHEM:MATTER-COPY FEP::LSOURCE)
                 (CHEM:MATTER-COPY FEP::LSOURCE)
                 (CHEM:MATTER-COPY FEP::LSOLV)))
(LEAP.SET-BOX:SET-BOX FEP::DECHARGE :VDW)
(CANDO:SAVE-MOL2 FEP::DECHARGE "AA-AB/ligand/decharge/decharge.mol2")
(LEAP.TOPOLOGY:SAVE-AMBER-PARM-FORMAT FEP::DECHARGE
                                      "AA-AB/ligand/decharge/decharge.parm7"
                                      "AA-AB/ligand/decharge/decharge.rst7")
(CORE:EXIT)
